### ISSUE TITLE
!bash

### ISSUE THREAD

**Issue by joey-kilgore** [cse-uprc/Bash-Bot#3]
**Describe the solution you'd like**
!bash and then all text after that is sent to a linux terminal.  
It would also be nice to send a number after it to relate to a different terminal. ie !bash1 controls a different terminal than !bash2.  

**Describe alternatives you've considered**
Nothing yet.

**Comment by jared-maki** [comment]
One idea i've had was that when the user wants to start a terminal session, Bash Bot would create a new terminal session tied to that specific user which could help prevent terminals colliding

**Comment by joey-kilgore** [comment]
The only problem with that is the pi's are relatively low powered, and with 30 people in the chat it could be a lot of things running.

**Comment by joey-kilgore** [comment]
So it seemed after some discussion that the easiest way to implement multiple terminals, would be to have multiple channels each dedicated to its own terminal. This discussion was between @joey-kilgore @jared-maki @Jacob-Hunt @jBenderToledo

**Comment by joey-kilgore** [comment]
This issue has become obsolete with the release of v1.0.0 and issue #9
